name: Merge Feature Branches to Development

on:
  push:
    branches:
      - "feature/*"

jobs:
  merge_to_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Merge into development
        run: |
          git fetch origin development
          git checkout development
          git merge --no-ff ${{ github.ref_name }} -m "Merge feature to development"
          git push origin development
