name: Promote Preview to Production

on:
  workflow_dispatch: # se ejecuta manualmente desde la pestaña Actions

jobs:
  promote_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout preview branch
        uses: actions/checkout@v4
        with:
          ref: preview

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Merge preview → production
        run: |
          git fetch origin production
          git checkout production
          git merge --no-ff origin/preview -m "Promote preview to production"
          git push origin production
